### ISSUE TITLE
To meetup or not to meetup

### ISSUE THREAD

**Issue by mikeal** [knode/node-meatspace#5]
I've been thinking a lot lately about less traditional "meetups" (lots of chairs facing forward while someone talks and we all eat pizza).

Some of the events that bring people together and seem to create a more lasting social fabric are the "drinkups" and other informal events.

When pulling the Calendar together I noticed all kinds of drinkups, study groups, beach hackathons, etc.

What are people's experience with less formal events vs. meetups?

**Comment by mikeal** [comment]
@diasdavid you just put together a lot of different events in Portugal, what's your experience been so far?

**Comment by daviddias** [comment]
What I can definitely say is that "winning someone else trust is not a easy thing", but those that come to a meetup, are definitely up to try, however most of the times they don't have the set of social "will" to get it started. I confirmed this idea again at Nodeconf.eu, I constantly jumped from group to group each time a coffee break, lunch or bus travel happened and I started to knock people's shoulder asking who they are and where they are coming from, people were talkative and had lot's of interesting stuff to share, but probably if I didn't start some of the times, the conversation would not exist.

So having this in mind, my conclusion is that you have to ignite the conversation, pizza and beer can be good, but most of the times people will gather in groups with the ones they already know.

In order to fight this, in the last (which was the first) Google DevFest in Portugal (March2013), I created a game which was called "Developer Bingo" which mainly, each person had a sheet of paper with 6 squares where they had to write 3 programming languages and 3 SDK/frameworks they use and love, after this step, they had to meet 6 different individuals that shared the same passion, know their names, job, town and the first four people who got all the six, had to shout BINGO! and won a prize (it was a Sigg bottle). Seems rather simpler, but the effect was extraordinary, 200 people in an amphitheater jumping from place to place to meet everyone, and they really had to meet, because in the end they had to prove by describing the 6 persons on the paper.
After this game, we had a barbecue before the big hackathon and workshops, so that everyone could get to know more each other and cross-introduce someone with similar tastes (it was fun!)

So my conclusion was - if you get devs to talk (even if only one minute about something substantially), they will become friends :)

Now other thought I have is that there can only be 2 goals of a meetup and you should not make a Hybrid, because you won't have time to pull everything off (unless it's a 24 hour ++ event), which are:
1. you create a meetup to get people together to talk
2. you create a meetup to get people talking about some new technology or system you want them to know about

The latter one requires lot's of hands on and a really focused experience towards the goal (not so much the social aspect),  I wish we had more of these here in Lisbon to increase the quality of technology produced (and the quality of the content in the meetups). As for the first one, you basically just need some 5 or 10 minutes flash talks to justify to the person that it's worthy to invest their time there, but in the end the good part is on the drinks or the long table dinner that usually happens after, that everyone enjoys and stays till 2 am talking :)

PS: The idea for Developer Bingo came from a 10 day Training for Trainers I had in Turkey October 2012, it was full of engineers but the focus was not dev, however I learned a lot of this activities to connect people from different cultures and backgrounds to get together and if I'm not wrong, this game and a lot more are described in this [bookA](http://www.amazon.com/Humorous-Training-Games-Business-Series/dp/0071357807) or this one [bookB](http://www.amazon.com/The-Big-Book-Icebreakers-Activities/dp/0071349847/ref=pd_sim_b_4)

**Comment by luk-** [comment]
I like the free pizza and beer aspect of traditional meetups. It's really hard to find good pizza in the bay area.

**Comment by luk-** [comment]
I was actually thinking it would be nice to have more "meetups" of people at coffee shops or bars either talking about stuff or just sitting and working on things independently. Environments like this are more natural when someone wants to share something or show someone how to do something.

**Comment by jhs** [comment]
The Bangkok Node.js meetup is off to a good start. However so far the format has had a very heavy "training" style. Somebody is in the front showing off LevelDB or whatever. But I want to defend the "formal" style.

I do not acknowledge the virtue of creating a "lasting social fabric." Right from the start, these words sound suspicious. Are we also leveraging content by curating the social graph? But I think I know what Mikeal means; and I agree with the idea but not the fabric metaphor. It is more like a city, where you have a slowly growing population, but individuals are in and out.

Anyway, there is also a virtue in just plain old teaching Node to as many people as possible. For every person looking for new drinking buddies, ten just want to learn a new tool, gain experience, and generally keep their ear to the ground about new technologies. (I imagine these people are rare in the Bay Area, and common outside the Bay Area.)

In my meetups, everybody wants to know what Node.js is good for and how it compares to Rails and Java and stuff. I make it very clear when you want Rails (any project you start today) and when you want Node (any project you start tomorrow). People are asking for essentially crash courses on Node fundamentals for real-time apps: event emitters, streams, web sockets. At least that is where the Node rubber meets the development road in these parts.

On the other hand, we do suffer badly from Asian presentation syndrome. I am very interested working on the fabric a bit. Thanks @diasdavid for your advice, I will try some of these ideas, and maybe have an "eatup" to help break the ice more. But yeah, to me, ice-breaking is only means to an end which is helping people write better software.

**Comment by thoward** [comment]
I very much agree with @diasdavid's sentiment about the two aspects of these kinds of gatherings: a) to be social b) to learn .. However I'm not sure that they are mutually exclusive. 

They both have a common, which is **sharing**. Sharing information, sharing experiences, sharing a friendship, sharing work on a project. Any situation that facilitates sharing between people will have the combined effect of building relationships and learning.

One of the dangers of focusing too much on either aspect in a single event is that you risk jeopardizing the other. 

Take the two proposed formats: the presentation and the drinkup as polar opposites. 

In the presentation, we're optimizing for "learning". An unapproachable speaker projects their knowledge to a crowd. The crowd learns, but has very little opportunity to share with the presenter or each other. A few minutes before/after while eating pizza is a small window for that interaction. Often attendees go to a bar afterward for the social aspect. Unfortunately, not everyone has that much time or comfort with that format so it's just as easy not to go.

In the drinkup, we're optimizing for "socializing". It's understood that the attendees all have a common background and set of interests (JS, or whatever). If there are 50 people, small groups form of say 5 members. Each group has a separate conversation. You'll walk away with a shared experience and feel more comfortable talking to those people again. 

But, for learning? Suppose 10 topics are discussed, with various levels of detail, complexity, etc. You will experience 1 or 2 of them, and have no idea what you will learn before hand, or even if the people attending/talking have any valuable knowledge of what's they are discussing. You may learn nothing but your peer's opinions about bicycles, coffee, or their workplace frustrations. Perhaps no technical content at all. 

On the upside, the barriers will be lower later when you want to talk to those people because of your shared social experience. Drinkups are cool too because they tend to draw a mixed crowd of folks with lots of technical background/interest, instead of the narrow crowd that a tech specific presentation tends to draw.

So.. there's nothing wrong with having both, but they aren't optimally efficient uses of time. What kind of events avoid the pitfalls of those approaches? Hackathons! Workshops! Minimally guided un-conferences! NodeBots Day! Things that involve small to mid-sized groups dealing with technical project topics, where attendee collaboration is a fundamental part of the activities.

We did this a lot with the ALT.NET meetups. Coder Society is also run with a similar model: building mock projects together to explore new technologies. A lot of this was based on the concept of Open Space, described here by Martin Fowler: http://www.martinfowler.com/bliki/OpenSpace.html

These kinds of events tend to be longer format, but don't have to be. They can also be coupled with the drinkup format or the preso format pretty easily to augment.

Here in Portland we have a bunch of random meetup nights. They have various names, but tend to follow the format of "lets meet at a bar/brew pub that is hacker friendly, and sit around coding, talking, and drinking beer together". These meetups are great, but I personally find that I either spend most of the time "heads down" getting coding done, or most of the time talking and getting very little hacking done. Either way, it's modal; I'm doing one or the other. Very rarely is there any solid collaboration at those events. It is a great way to keep up with your community members, especially across languages/topics. I can see my JS friends, Python friends, Ruby friends and .NET friends all in the same room, which is great. 

Anyhow -- @diasdavid's other point about intentionally ice-breaking and connecting is hugely important. Being a social integrator really breaks down barriers. If you're the one who has met everyone, then anyone feels comfortable walking up to you and, through you, meeting someone else. Big time win for breaking down social awkwardness.
